version: 2.1

jobs:
  run-selenium:
    docker:
      - image: cimg/python:3.10  # Python image
    steps:
      - checkout

      - run:
          name: Install Chrome
          command: |
            sudo apt update
            sudo apt install -y wget unzip curl
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install ChromeDriver
          command: |
            wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/linux64/chromedriver-linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            chmod +x /usr/local/bin/chromedriver

      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run Python script
          command: python your_script.py

workflows:
  version: 2
  run-on-push:
    jobs:
      - run-selenium
