version: 2.1

jobs:
  run-selenium:
    docker:
      - image: cimg/python:3.10  # Python image
    steps:
      - checkout

      - run:
          name: Install Chrome
          command: |
            sudo apt update
            sudo apt install -y wget unzip curl
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - run:
          name: Install ChromeDriver
          command: |
            wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip
            ls -l  # Debug: Show extracted files
            ls -l chromedriver-linux64/  # Debug: Show contents of the folder
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver
            chromedriver --version  # Debug: Verify installation

      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run Python script
          command: python app.py

workflows:
  version: 2
  run-on-push:
    jobs:
      - run-selenium
